<?php

$string['pluginname'] = 'Modify sections';

// control panel hook text display
$string['modify_course_sections'] = 'Modify site menu sections';
$string['modify_course_sections_post'] = '';

$string['addnewsection'] = 'Add new section';
$string['deletingcontents'] = 'Delete content';

$string['additional_options'] = 'Additional options';
$string['hideautogeneratedcontent'] = 'Do not display auto-generated links';

// Javascript strings
$string['new_sectnum'] = 'New';
$stirng['default_new_section'] = 'New section';
$string['section'] = 'Section';
$string['title'] = 'Title';
$string['hide'] = 'Hide';
$string['delete'] = 'Delete';
$string['landing_page'] = 'Landing page';

$string['newsection'] = 'New section';
$string['couldnotdeletesection'] = 'The section "{$a->name}" could not be deleted because it is not empty. Please empty the section before deleting it.';
$string['deletesectioncontents'] = 'At least one of the section(s) you are deleting have content. Please check that these are the changes you wish to make.';
$string['tbdel'] = 'To delete:';
$string['deleteconfirm'] = 'Delete content';

$string['successmodify'] = 'The sections have been successfully updated.';
$string['failuremodify'] = 'There was an error writing records to the database. Your modifications were not saved.';

// Alert for section mismatch.
$string['alertnumsections'] = 'There are more sections for this course than are currently being displayed. Would you like to show these missing sections by increasing the number of sections avaiable for displaying?';
$string['successnumsections'] = 'Successfully adjusted the number of sections for the course.';
$string['failurenumsections'] = 'There was a problem in adjusting the number of sections for the course. Please contact system administrator.';
$string['buttonnumsections'] = 'Adjust number of sections';