<?php
class Elluminate_WS_Utils {
   //The startTime and endTime generated by PHP are in seconds since Epoch,
   //SAS wants the times to be sent in milliseconds so we multiply by 1000
   //to keep the format correct.
   public static function convertPHPDateToSASDate($phpDate) {
      return $phpDate * 1000;
   }

   //The creationDate generated by PHP are in seconds (int) since Epoch,
   //SAS sends the create date in milliseconds (long) so we truncate the date
   //to 10 characters to get the int value.
   public static function convertSASDateToPHPDate($sasDate) {
      return substr($sasDate, 0, 10);
   }
}